/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   MOTD.cpp                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: esommier <esommier@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/10/05 12:08:21 by esommier          #+#    #+#             */
/*   Updated: 2022/11/22 21:36:37 by esommier         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

# include "ircCommands.hpp"

void    	MOTD(Command &command)// Parameters: [<target>]
{
    std::vector<std::string> args;
    std::string motd;
    User    u = command.getUser();

   
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTDSTART + std::string(" ") + u.getNickname() + std::string(" ") + RPL_MOTDSTART(u.getNickname()));
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                                                                                              ░░▒▒▒▒              ░░▒▒                        ░░");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                                                                                              ░░▒▒▒▒              ░░▒▒                        ░░");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                                                                                            ▒▒▒▒          ░░            ░░░░▒▒            ▒▒▒▒  ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                                                                                  ▒▒                                    ▒▒▒▒▒▒          ▒▒▒▒▒▒  ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                                                                                  ▒▒                                    ▒▒▒▒▒▒          ▒▒▒▒▒▒  ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                                                                                                                      ▒▒▒▒▒▒▒▒    ▒▒▒▒▒▒▒▒▒▒▒▒  ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                                                                  ▒▒        ▒▒          ░░    ▒▒▒▒▒▒▒▒▒▒░░          ▒▒▒▒░░▒▒▒▒  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒  ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                                                ▒▒▒▒▒▒                          ░░        ▒▒▒▒░░░░░░░░░░▒▒░░      ▒▒▒▒▒▒░░▒▒▒▒▒▒▒▒▒▒░░░░░░░░▒▒▒▒");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                                            ▒▒▓▓▓▓▓▓▓▓▓▓                              ▒▒▒▒░░░░░░        ░░▒▒░░    ▒▒▒▒░░░░░░▒▒▒▒░░░░░░░░░░░░▒▒▒▒");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                                          ▒▒▓▓▓▓▓▓▓▓▓▓▓▓░░                            ▒▒░░░░              ░░░░    ▒▒▒▒░░░░░░░░░░          ░░▒▒▒▒");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                                        ▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░                        ░░░░░░░░░░            ░░▒▒▒▒  ▒▒░░░░░░░░              ░░▒▒▒▒");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                                      ░░▓▓▓▓▓▓▓▓▓▓██████▓▓▒▒                    ░░  ░░░░░░░░▒▒░░            ░░▒▒  ▒▒░░░░                  ░░▒▒▒▒");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                                    ▒▒▓▓▓▓▓▓▓▓████▓▓▓▓▓▓▓▓▓▓                  ▒▒░░          ▒▒░░            ░░▒▒▒▒▒▒░░                    ░░▒▒▒▒");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                                  ▓▓▓▓▓▓▓▓▓▓████▓▓▓▓▓▓▓▓██▓▓          ▒▒    ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░              ░░▒▒▒▒░░░░                  ░░░░▒▒▒▒");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                                ▒▒▓▓▓▓▓▓▓▓████▓▓▓▓▓▓▓▓██▓▓        ░░      ░░▒▒░░▒▒░░░░░░░░░░                ░░▒▒░░░░                  ░░░░░░▒▒  ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                              ▒▒▓▓▓▓▓▓▓▓████▓▓▓▓▓▓▓▓▓▓▓▓                ░░▒▒▒▒░░░░░░░░░░                    ░░░░░░                  ░░░░▒▒▒▒▒▒  ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                            ▒▒▓▓▓▓▓▓▓▓▓▓████▓▓▒▒▓▓▒▒██                ░░▒▒░░░░░░░░                                                ░░░░▒▒▒▒▒▒    ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                          ▒▒▓▓▓▓▓▓▓▓▓▓████▓▓▒▒▒▒▒▒▓▓▓▓      ░░        ▒▒░░░░                                                    ░░░░▒▒▒▒▒▒      ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                        ▓▓▓▓▓▓▓▓▓▓▓▓▓▓██▓▓▒▒▒▒▒▒▒▒▒▒██            ▒▒▒▒░░░░                                                      ░░░░▒▒▒▒        ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                      ▓▓▓▓▓▓▓▓▓▓▓▓▒▒▓▓██▓▓▒▒▒▒▒▒▒▒██              ▒▒░░░░░░                                                    ░░░░▒▒░░          ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                  ░░▓▓▓▓▓▓▓▓▓▓▓▓▒▒▓▓██▓▓▒▒▒▒▒▒▒▒▒▒▒▒            ▒▒░░░░                                                        ░░▒▒▒▒            ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                          ░░░░░░░░░░▓▓▓▓▓▓▓▓▓▓▒▒▓▓▓▓██▓▓▒▒░░░░░░▓▓██          ▒▒▒▒                                                          ░░░░▒▒▒▒            ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                        ░░░░░░░░██▓▓▓▓▓▓▓▓▓▓▒▒▓▓▓▓▓▓██▓▓░░░░  ░░██          ▒▒▒▒▒▒░░░░                                                  ░░░░░░▒▒░░              ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                              ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░        ░░          ▒▒▒▒░░░░░░                                              ░░░░░░▒▒▒▒                  ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                            ░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░        ░░          ▒▒░░░░░░░░░░                                          ░░░░░░░░▒▒▒▒                  ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                        ░░░░░░▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░▓▓▓▓          ░░▓▓          ▒▒░░░░                    ░░░░░░░░░░  ░░    ░░░░░░░░░░░░░░░░░░▒▒        ░░        ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                      ░░░░░░  ░░▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░██▓▓      ░░░░▓▓▓▓          ▒▒▒▒░░          ░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░                ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                      ░░░░░░░░░░▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░  ██    ░░░░░░░░▒▒▓▓          ▒▒░░              ░░░░░░░░░░░░░░▒▒░░░░              ▒▒▒▒▒▒▒▒▒▒░░              ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                    ░░░░  ░░░░░░▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░██▓▓▒▒░░░░░░░░░░▓▓▓▓          ▒▒                        ░░░░▒▒▒▒▒▒░░                ▒▒▒▒▒▒░░              ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                  ░░░░  ░░░░░░▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░  ████▓▓▒▒▒▒▒▒░░░░██▓▓          ▒▒░░                  ░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒                                ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                ░░░░  ░░░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░  ██▒▒▓▓▓▓▒▒▒▒░░░░▓▓▓▓        ▒▒▒▒░░                    ░░░░▒▒░░            ▒▒                          ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":              ░░░░  ░░░░  ▓▓▓▓▓▓▓▓░░░░▓▓▓▓▓▓▒▒░░░░░░░░░░░░  ████▓▓▓▓▓▓▒▒░░▓▓▓▓▓▓        ▒▒▒▒            ░░░░░░░░░░░░░░▒▒                ░░        ░░            ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":            ░░░░  ░░    ▓▓▓▓▓▓▓▓▒▒░░▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░  ██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓            ▒▒▒▒░░░░░░░░░░░░▒▒▒▒░░░░░░░░░░                                      ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":          ░░░░  ░░      ▓▓▓▓▓▓▒▒░░▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░▒▒░░░░░░░░  ██████▓▓▓▓▓▓██▓▓                ▒▒▒▒▒▒░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒░░                                      ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":        ░░░░  ░░          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░▒▒▒▒░░░░░░    ████████▓▓                        ▒▒▒▒░░░░▒▒    ▒▒▒▒▒▒▒▒░░                ▒▒░░              ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":      ░░░░  ░░                ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░▒▒▒▒          ██████                              ▒▒▒▒▒▒░░        ▒▒░░  ▒▒      ▒▒▒▒▒▒▒▒▒▒▒▒            ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":    ░░░░  ░░                ░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░▒▒▒▒▒▒░░░░▒▒                        ░░            ▒▒▒▒                        ▒▒▒▒  ▒▒▒▒            ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":    ░░░░░░                  ░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░  ▒▒                                                ▒▒▒▒                                            ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":  ░░░░░░                  ░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░  ▒▒                                                    ░░                                          ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":  ░░░░                    ░░  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░  ▒▒                                        ░░                                                      ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":  ░░                      ░░    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░  ▒▒▒▒                                                                                              ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                              ░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░    ▒▒                                                                                              ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                            ░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░    ▒▒                                                                                            ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                            ░░░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░    ▒▒                                                                                          ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                              ░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░    ░░                                                                                        ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                              ░░    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░  ▒▒░░                                       ██╗██████╗  ██████╗                            ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                  ░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░  ▒▒▒▒                                     ██║██╔══██╗██╔════╝                            ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                  ░░  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒░░░░░░░░░░░░    ▒▒▒▒                                   ██║██████╔╝██║                                 ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                  ░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒░░░░░░░░░░░░    ▒▒░░░░                               ██║██╔══██╗██║                                 ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                  ░░░░  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░  ░░▒▒▒▒                               ██║██║  ██║╚██████╗                            ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                    ░░  ██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░░░░░▒▒▒▒                             ╚═╝╚═╝  ╚═╝ ╚═════╝                            ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░░░    ▒▒                                                                            ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                      ░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░░░    ▒▒                                                                          ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                      ░░  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░░░  ▒▒                                                                          ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                    ░░░░  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░░░    ▒▒                                                                        ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                                          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░░░  ▒▒                                                                        ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                              ░░░░░░░░  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░  ▒▒                                                                        ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                      ░░░░        ░░  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░  ▒▒▒▒                                                                      ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                    ░░░░░░░░    ████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░  ▒▒▒▒                                                                      ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                        ░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░  ▒▒▒▒                                                                      ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":              ░░░░░░    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░  ▒▒▒▒                                                                      ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":            ░░░░░░  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░  ▒▒░░                                                                      ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":                  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░░░    ▒▒▒▒                                                                      ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_MOTD + std::string(" ") + u.getNickname() +  std::string(" ") + ":            ░░  ██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░  ▒▒▒▒▒▒                                                                      ");
    u.message_reply(u.getFd(), u.getHostname(), CODE_RPL_ENDOFMOTD + std::string(" ") + u.getNickname() + std::string(" ") + RPL_ENDOFMOTD());
}

void    	motd(int fd, User *u)// Parameters: [<target>]
{
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTDSTART + std::string(" ") + u->getNickname() + RPL_MOTDSTART(u->getNickname()));
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                                                                                              ░░▒▒▒▒              ░░▒▒                        ░░");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                                                                                              ░░▒▒▒▒              ░░▒▒                        ░░");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                                                                                            ▒▒▒▒          ░░            ░░░░▒▒            ▒▒▒▒  ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                                                                                  ▒▒                                    ▒▒▒▒▒▒          ▒▒▒▒▒▒  ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                                                                                  ▒▒                                    ▒▒▒▒▒▒          ▒▒▒▒▒▒  ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                                                                                                                      ▒▒▒▒▒▒▒▒    ▒▒▒▒▒▒▒▒▒▒▒▒  ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                                                                  ▒▒        ▒▒          ░░    ▒▒▒▒▒▒▒▒▒▒░░          ▒▒▒▒░░▒▒▒▒  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒  ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                                                ▒▒▒▒▒▒                          ░░        ▒▒▒▒░░░░░░░░░░▒▒░░      ▒▒▒▒▒▒░░▒▒▒▒▒▒▒▒▒▒░░░░░░░░▒▒▒▒");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                                            ▒▒▓▓▓▓▓▓▓▓▓▓                              ▒▒▒▒░░░░░░        ░░▒▒░░    ▒▒▒▒░░░░░░▒▒▒▒░░░░░░░░░░░░▒▒▒▒");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                                          ▒▒▓▓▓▓▓▓▓▓▓▓▓▓░░                            ▒▒░░░░              ░░░░    ▒▒▒▒░░░░░░░░░░          ░░▒▒▒▒");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                                        ▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░                        ░░░░░░░░░░            ░░▒▒▒▒  ▒▒░░░░░░░░              ░░▒▒▒▒");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                                      ░░▓▓▓▓▓▓▓▓▓▓██████▓▓▒▒                    ░░  ░░░░░░░░▒▒░░            ░░▒▒  ▒▒░░░░                  ░░▒▒▒▒");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                                    ▒▒▓▓▓▓▓▓▓▓████▓▓▓▓▓▓▓▓▓▓                  ▒▒░░          ▒▒░░            ░░▒▒▒▒▒▒░░                    ░░▒▒▒▒");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                                  ▓▓▓▓▓▓▓▓▓▓████▓▓▓▓▓▓▓▓██▓▓          ▒▒    ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░              ░░▒▒▒▒░░░░                  ░░░░▒▒▒▒");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                                ▒▒▓▓▓▓▓▓▓▓████▓▓▓▓▓▓▓▓██▓▓        ░░      ░░▒▒░░▒▒░░░░░░░░░░                ░░▒▒░░░░                  ░░░░░░▒▒  ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                              ▒▒▓▓▓▓▓▓▓▓████▓▓▓▓▓▓▓▓▓▓▓▓                ░░▒▒▒▒░░░░░░░░░░                    ░░░░░░                  ░░░░▒▒▒▒▒▒  ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                            ▒▒▓▓▓▓▓▓▓▓▓▓████▓▓▒▒▓▓▒▒██                ░░▒▒░░░░░░░░                                                ░░░░▒▒▒▒▒▒    ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                          ▒▒▓▓▓▓▓▓▓▓▓▓████▓▓▒▒▒▒▒▒▓▓▓▓      ░░        ▒▒░░░░                                                    ░░░░▒▒▒▒▒▒      ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                        ▓▓▓▓▓▓▓▓▓▓▓▓▓▓██▓▓▒▒▒▒▒▒▒▒▒▒██            ▒▒▒▒░░░░                                                      ░░░░▒▒▒▒        ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                      ▓▓▓▓▓▓▓▓▓▓▓▓▒▒▓▓██▓▓▒▒▒▒▒▒▒▒██              ▒▒░░░░░░                                                    ░░░░▒▒░░          ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                  ░░▓▓▓▓▓▓▓▓▓▓▓▓▒▒▓▓██▓▓▒▒▒▒▒▒▒▒▒▒▒▒            ▒▒░░░░                                                        ░░▒▒▒▒            ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                          ░░░░░░░░░░▓▓▓▓▓▓▓▓▓▓▒▒▓▓▓▓██▓▓▒▒░░░░░░▓▓██          ▒▒▒▒                                                          ░░░░▒▒▒▒            ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                        ░░░░░░░░██▓▓▓▓▓▓▓▓▓▓▒▒▓▓▓▓▓▓██▓▓░░░░  ░░██          ▒▒▒▒▒▒░░░░                                                  ░░░░░░▒▒░░              ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                              ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░        ░░          ▒▒▒▒░░░░░░                                              ░░░░░░▒▒▒▒                  ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                            ░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░        ░░          ▒▒░░░░░░░░░░                                          ░░░░░░░░▒▒▒▒                  ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                        ░░░░░░▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░▓▓▓▓          ░░▓▓          ▒▒░░░░                    ░░░░░░░░░░  ░░    ░░░░░░░░░░░░░░░░░░▒▒        ░░        ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                      ░░░░░░  ░░▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░██▓▓      ░░░░▓▓▓▓          ▒▒▒▒░░          ░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░                ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                      ░░░░░░░░░░▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░  ██    ░░░░░░░░▒▒▓▓          ▒▒░░              ░░░░░░░░░░░░░░▒▒░░░░              ▒▒▒▒▒▒▒▒▒▒░░              ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                    ░░░░  ░░░░░░▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░██▓▓▒▒░░░░░░░░░░▓▓▓▓          ▒▒                        ░░░░▒▒▒▒▒▒░░                ▒▒▒▒▒▒░░              ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                  ░░░░  ░░░░░░▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░  ████▓▓▒▒▒▒▒▒░░░░██▓▓          ▒▒░░                  ░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒                                ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                ░░░░  ░░░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░  ██▒▒▓▓▓▓▒▒▒▒░░░░▓▓▓▓        ▒▒▒▒░░                    ░░░░▒▒░░            ▒▒                          ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":              ░░░░  ░░░░  ▓▓▓▓▓▓▓▓░░░░▓▓▓▓▓▓▒▒░░░░░░░░░░░░  ████▓▓▓▓▓▓▒▒░░▓▓▓▓▓▓        ▒▒▒▒            ░░░░░░░░░░░░░░▒▒                ░░        ░░            ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":            ░░░░  ░░    ▓▓▓▓▓▓▓▓▒▒░░▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░  ██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓            ▒▒▒▒░░░░░░░░░░░░▒▒▒▒░░░░░░░░░░                                      ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":          ░░░░  ░░      ▓▓▓▓▓▓▒▒░░▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░▒▒░░░░░░░░  ██████▓▓▓▓▓▓██▓▓                ▒▒▒▒▒▒░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒░░                                      ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":        ░░░░  ░░          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░▒▒▒▒░░░░░░    ████████▓▓                        ▒▒▒▒░░░░▒▒    ▒▒▒▒▒▒▒▒░░                ▒▒░░              ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":      ░░░░  ░░                ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░▒▒▒▒          ██████                              ▒▒▒▒▒▒░░        ▒▒░░  ▒▒      ▒▒▒▒▒▒▒▒▒▒▒▒            ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":    ░░░░  ░░                ░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░▒▒▒▒▒▒░░░░▒▒                        ░░            ▒▒▒▒                        ▒▒▒▒  ▒▒▒▒            ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":    ░░░░░░                  ░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░  ▒▒                                                ▒▒▒▒                                            ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":  ░░░░░░                  ░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░  ▒▒                                                    ░░                                          ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":  ░░░░                    ░░  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░  ▒▒                                        ░░                                                      ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":  ░░                      ░░    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░  ▒▒▒▒                                                                                              ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                              ░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░    ▒▒                                                                                              ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                            ░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░    ▒▒                                                                                            ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                            ░░░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░    ▒▒                                                                                          ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                              ░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░    ░░                                                                                        ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                              ░░    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░  ▒▒░░                                       ██╗██████╗  ██████╗                            ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                  ░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░  ▒▒▒▒                                     ██║██╔══██╗██╔════╝                            ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                  ░░  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒░░░░░░░░░░░░    ▒▒▒▒                                   ██║██████╔╝██║                                 ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                  ░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒░░░░░░░░░░░░    ▒▒░░░░                               ██║██╔══██╗██║                                 ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                  ░░░░  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░  ░░▒▒▒▒                               ██║██║  ██║╚██████╗                            ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                    ░░  ██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░░░░░▒▒▒▒                             ╚═╝╚═╝  ╚═╝ ╚═════╝                            ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░░░    ▒▒                                                                            ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                      ░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░░░    ▒▒                                                                          ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                      ░░  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░░░  ▒▒                                                                          ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                    ░░░░  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░░░    ▒▒                                                                        ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                                          ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░░░  ▒▒                                                                        ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                              ░░░░░░░░  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░  ▒▒                                                                        ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                      ░░░░        ░░  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░░░  ▒▒▒▒                                                                      ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                    ░░░░░░░░    ████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░  ▒▒▒▒                                                                      ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                        ░░░░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░  ▒▒▒▒                                                                      ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":              ░░░░░░    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░  ▒▒▒▒                                                                      ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":            ░░░░░░  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░░░░░  ▒▒░░                                                                      ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":                  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒░░░░░░░░░░░░    ▒▒▒▒                                                                      ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_MOTD + std::string(" ") + u->getNickname() +  std::string(" ") + ":            ░░  ██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒░░░░░░░░░░░░  ▒▒▒▒▒▒                                                                      ");
    u->message_reply(fd, u->getHostname(), CODE_RPL_ENDOFMOTD +  std::string(" ") + u->getNickname() + RPL_ENDOFMOTD());
}